# @package _global_
RNN:
  RNN_TYPE: arelit
  N_LAYERS: 2
  D_MODEL: 128
  D_HEAD: 64
  D_FFC: 64
  N_HEADS: 4
  ETA: 4
  R: 2
LR: 0.00025
NUM_ENVS: 4
NUM_STEPS: 128
TOTAL_TIMESTEPS: 500000
UPDATE_EPOCHS: 4
LOG_INTERVAL: 10  # Log every 10 updates
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ENV_NAME: craftax
ANNEAL_LR: true
DEBUG: true
OPTIMISTIC_RESETS: false
HIDDEN: 128
USE_WANDB: true
WANDB_PROJECT: purejaxrl
WANDB_TAGS: null
